### ISSUE TITLE
Is this an old article?

### ISSUE THREAD

**Issue by A-j-K** [qbox-io/qbox-elasticsearch-tutorial#2]
V 6.6.1

Bulk input:-
```bash
curl -s -H 'Content-Type: application/x-ndjson' -XPOST --data-binary "@disney-data" localhost:9200/_bulk; echo
```

Search:-
```bash
curl -XGET 'localhost:9200/disney/character/_search?pretty=true'
```

**Comment by doombongo** [comment]
Yes, it's 5 years old, I haven't made any commits since it was pushed up 5 year ago. I'll close this issue but I'll be sure to add a note to re-create a more "current" version for introduction because I think it would be good to have.
